import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getSession, handleToggleSlideBar } from "./lib/session";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./components/layout/appSideBar";
import { SidebarTriggerWrapper } from "./components/layout/sideBarTriggerWrapper";
import { cn } from "@/lib/utils";
import MainLayout from "./components/layout/mainLayout";
import Providers from "./providers";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session  = await getSession()
  const collapsed = session ? (await handleToggleSlideBar() || true) : false
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <SidebarProvider defaultOpen={collapsed}>
            <AppSidebar session={session}/>
            <MainLayout session={session}>{children}</MainLayout>
          </SidebarProvider>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
